#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

# Stackage LTS Haskell 22.44 (ghc-9.6.7)
resolver: lts-22.44

local-bin-path: .

nix:
  path: [nixpkgs=../../nixpkgs]

